#In this file we will define the user defined markers for pytest framework. 
#These markers will be used to categorize the test cases based on their functionality and purpose.

[pytest]
addopts = --html=report.html
markers =
    smoke: smoke test cases
    trading: trading test cases
    rande: retail and ecommerse
    mob:mobile app and devlopment
    ai:ai tab

 -m